### PR TITLE
APOGEE-2 Selection Function(s)

### PR DESCRIPTION
**Pull request by jmackereth**
Probably about time we started looking at merging this back into the main repo, especially since it is now in use by a few people.

I think this is almost ready to go, but I can't guarantee that it will be seamlessly backward-compatible with old code using the selection function, but lets see...

@jamesmlane - since you are actively using this, perhaps if you test and communicate any problems here?

### CODE REVIEW

**Comment by jobovy** [comment]
I think we can safely merge this into ``ap2sf``, but we might want to be more careful in going to ``master``. Maybe I'll tag a version of ``master`` before merging in the ``ap2sf`` branch, so there's a working version that's easy to find.

This is both the DR14 and DR16 SFs? I thought we were going to start with just DR14, but perhaps they are just intertwined too much.

I believe I have a notebook somewhere (based on one of yours) that goes through the SF functionality, so I will try running that again.

**Comment by jobovy** [comment]
@jmackereth -- I'm looking at this and all looks pretty good, but I need the new observation logs, because I don't think I have them (can't run the code without them). We'll also have to put all necessary obslogs (both DR14 and DR16) on zenodo or something (did you send them to James)?

Not very urgent, but when you have a moment!

**Comment by jmackereth** [comment]
@jobovy - great, thanks! Im wondering whether it might be simpler to include the obslogs in the actual repo, since they are no larger than a few 100KB. I didn't know if there might be some issue with doing that though? 

I still have some stuff to fix with byte/string conversion issues, but hopefully will get that done quickly. The main thing now is that I'll need to test that everything looks ok with the new allDesign/allField files... more soon.

**Comment by jobovy** [comment]
Yes, maybe it's easier indeed to just include the obslogs in the repository, maybe just as a folder in ``apogee/tools`` then, so they can easily be accessed by the read functions. Will then have to make sure to include this in the ``package_data`` section of the ``setup.py`` file so these files get copied over when the package is installed.

No rush on this, just let me know when I should look at this again.

**Comment by jmackereth** [comment]
Right - I *think* this is all ready to be pulled in now. The updates to the `allField`, `allDesign` and `allPlate` (new) files made things slightly non-trivial. So you may want to check that you are happy with the changes in that regard. The main change is that there is now an option in the `read.apogeePlate` which 'standardises' the allPlate file to resemble the old apogeePlate files (see [here](https://github.com/jmackereth/apogee/blob/c7ed4385ae5645ed642058fbaf940135352f61ab/apogee/tools/read.py#L750-L767)).

**Comment by jmackereth** [comment]
Ah - the last thing that needs to be done is to update the ReadMe, ill do this in the next few days....

**Comment by jobovy** [comment]
I had made some changes for DR16 that I hadn't pushed yet and which resulted in a conflict. In fixing that, I seem to have merged this PR! Anyway, the main one (to ``master``) is still open. I'm running my notebook now to check whether everything works...

**Comment by jobovy** [comment]
Most things seem to work, but I can't get things like
```
apo.apo2Nsel.plot_obs_progress(cohort='short',gcf=True)
```
to work, does that work for you? The error I'm getting is
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-13da84412d34> in <module>()
      7 bovy_plot.bovy_text(r'$\mathrm{APOGEE\!-\!1}$',size=18.,title=True)
      8 subplot(2,2,4)
----> 9 apo.apo2Ssel.plot_obs_progress(cohort='short',gcf=True)
     10 bovy_plot.bovy_text(r'$\mathrm{APOGEE\!-\!2}$',size=18.,title=True)
     11 subplot(2,2,2)

~/Repos/apogee/apogee/select/apogeeSelect.py in plot_obs_progress(self, cohort, xrange, yrange, ms, add_mean_label, add_cohort_label, incl_not_started, cmap, gcf)
    641                                 vmin=0.,vmax=1.,
    642                                 crange=[0.,1.],
--> 643                                 zorder=1)
    644         if add_mean_label:
    645             bovy_plot.bovy_text(r'$\mathrm{average\ completeness}: %.0f\,\%%$' %

~/Repos/galpy/galpy/util/bovy_plot.py in bovy_plot(*args, **kwargs)
    293             xlimits=(numpy.array(args[0]).min(),numpy.array(args[0]).max())
    294         else:
--> 295             xlimits=(args[0].min(),args[0].max())
    296     ylimits= kwargs.pop('yrange',None)
    297     if ylimits is None:

/usr/local/lib/python3.6/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims, initial)
     30 def _amin(a, axis=None, out=None, keepdims=False,
     31           initial=_NoValue):
---> 32     return umr_minimum(a, axis, None, out, keepdims, initial)
     33 
     34 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,

ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by jmackereth** [comment]
Hmm... I just tested this again and it does work for me. There were a few tiny changes that weren't pushed up to the branch (now pushed up), but im not entirely sure these will fix that issue..

I'm not even completely sure what that error message means, if im honest! I'll see if I can replicate.

**Pull request merged**
