### PR TITLE
Made wavelength ranges data release dependent

### PR DESCRIPTION
**Pull request by npricejones**
Also updated all functions/decorators that had DR12 bounds hard coded in.

### CODE REVIEW

**Comment by henrysky** [comment]
The bound for DR14 (and DR13) should be [246, 3274, 3585, 6080, 6344, 8335] which is 7514 pixels in total??

**Comment by jobovy** [comment]
Thanks, this looks great. But I think @henrysky is correct that the indices aren't quite right, e.g., for DR13
```
import apogee.tools.read as apread
aspcap_spec, hdr= apread.aspcapStar(4102,'2M21353892+4229507',ext=1,aspcapWavegrid=True)
ap_spec, hdr= apread.aspcapStar(4102,'2M21353892+4229507',ext=1,aspcapWavegrid=False)
print('Start of the blue chip is fine')
print(ap_spec[245:248])
print(aspcap_spec[0:2])
print('First two of the following should match up I think at the end of the blue chip')
print(ap_spec[3272:3275])
print(aspcap_spec[3026:3029])
```
gives
```
Start of the blue chip is fine
[ 0.          0.76672399  0.83350998]
[ 0.76672399  0.83350998]
First two of the following should match up I think at the end of the blue chip
[ 0.88915598  0.88799298  0.        ]
[ 0.88915598  0.91637599  0.83431602]
```

I think the upper limits probably all just need +1 added for correct indexing?

**Comment by npricejones** [comment]
I've fixed the upper limits of the ranges so that 

```
import apogee.tools.read as apread
aspcap_spec, hdr= apread.aspcapStar(4102,'2M21353892+4229507',ext=1,aspcapWavegrid=True)
ap_spec, hdr= apread.aspcapStar(4102,'2M21353892+4229507',ext=1,aspcapWavegrid=False)
print('Start of the blue chip is fine')
print(ap_spec[245:248])
print(aspcap_spec[0:2])
print('First two of the following should match up I think at the end of the blue chip')
print(ap_spec[3272:3275])
print(aspcap_spec[3026:3029])
```

gives
```
Start of the blue chip is fine
[ 0.          0.76672399  0.83350998]
[ 0.76672399  0.83350998]
First two of the following should match up I think at the end of the blue chip
[ 0.88915598  0.88799298  0.        ]
[ 0.88915598  0.88799298  0.91637599]
```

**Comment by jobovy** [comment]
Thanks! I've checked the other chip edges and they seem all correct to me, so I will merge this unless I hear otherwise...

**Pull request merged**
